### ISSUE TITLE
benim readmem calindi mi

### ISSUE THREAD

**Issue by sudis** [wioenena-q/JS-WioDB#1]
**birisiyle konusuyodum sonra adini bilmiyorum benim  readmemi calmis sonra sen kimden caldin diye onu koseye sıkıstırdım adını verdi bıc atarim valla he**

**Comment by wioenena-q** [comment]
yok

**Comment by sudis** [comment]
Çalmışsın işte kabul et.

**Comment by sudis** [comment]
**kardeşim bak readmemi rahat bırak. son ikazım**

**Comment by sudis** [comment]
sa arkadaşım bak readmemi bırakman için son ikazım. Eğer bırakmazsan alttakileri yaparım.

- [x] seni yok ederim

Gayet yeterli mi?

**Comment by sudis** [comment]
Readmemi silcen mi artık??
